# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'fastlane'
# gemspec path: File.expand_path('..\\..\\win-fastlane')
